#!/bin/bash
#
# Take new files from a list of directories, give them show titles and content, the "podcast" genre, and FTP them up to the Wordpress site

FTP_SERVER=web519.webfaction.com
FTP_DIR="webapps/rfp_wp/wp-content/uploads/mp3-to-post"
FTP_USER=tescher
LOCALDIR=/rfpserver
TEMP_DIR=~/temp
PODCAST_GENRE_DEFAULT=podcast     # how to tag mp3s for the podcast blog feed
MARKER_COMMENT=podcastuploaded  #Comment that signals file looked at
START_AFTER_DATE=2016-03-01

declare -A podcasts
podcasts["Mushing Radio"]="Mushing Radio|From Dog Talk Radio|mushingradio"
podcasts["Classics"]="Classical Music Radio|Music Classics|uncategorized"
podcasts["Radio Book Club"]="Radio Book Club|Latest book discussion moderated by Judy Gette|bookclub"

cd ${LOCALDIR}

for dir in "${!podcasts[@]}"
do
  if [ -d "${dir}" ]; then
    cd "${dir}"
    IFS="|"; read -ra podcast_info <<< "${podcasts[${dir}]}"
    if [ -n "${podcast_info[2]}" ]
    then
      podcast_genre="${podcast_info[2]}"
    else
      podcast_genre="${PODCAST_GENRE_DEFAULT}"
    fi
    echo "${podcast_genre}"
    touch timestamp -d ${START_AFTER_DATE}
    find . -newer timestamp -name "*.mp3" | while read fname; do
      fname=$(basename "${fname}")
      echo Looking at ${fname}
      if ! mid3v2 -l "${fname}" | grep -q ${MARKER_COMMENT}; then
        echo New file found: ${fname}
        filedata=`stat -c%y "${fname}"`
        IFS=" "; read -ra filedata_array <<< "${filedata}"
        filedate=`date -d ${filedata_array[0]} +%m/%d/%Y`
        cp "${fname}" "${TEMP_DIR}"
        mid3v2 --delete-frames=COMM "${TEMP_DIR}/${fname}"
        mid3v2 -g "${podcast_genre}" -t "${podcast_info[0]} ${filedate}" -c "${podcast_info[1]}" "${TEMP_DIR}/${fname}"
        sftp ${FTP_USER}@${FTP_SERVER}:${FTP_DIR} <<< $"put \"${TEMP_DIR}/${fname}\""
        mid3v2 -c "${MARKER_COMMENT}" "${fname}"
        rm "${TEMP_DIR}/${fname}"
      fi
    done
  fi
done
